#!/bin/sh

if [ "$#" -ne "1" ]
then
	cat <<-tac
		USAGE: $0 <installed | recommended | suggested>

		List all currently installed, recommended, or suggested Debian packages.

		Note that the recommended and suggested commands do not filter out installed packages.
		If this is desired, the user may accomplish it using the comm utility.
	tac
	exit 1
fi

depends() {
	local status="$1"
	apt-cache depends `cat` | sed -n "s/.*$status: \(\S\+\).*/\1/p" | sort | uniq
}

case "$1" in
installed)
	apt list --installed 2>/dev/null | tail -n+2 | cut -d/ -f1 | sort
	;;
recommended)
	"$0" installed | depends Recommends
	;;
suggested)
	"$0" installed | depends Suggests
	;;
*)
	exec "$0"
	;;
esac
