#!/bin/sh

if [ "$#" -ne "1" ]
then
	cat <<-tac
		USAGE: $0 <path to executable>

		Given one executable, finds the next thusly-named executable in the search path.
	tac
	exit 1
fi

base="`basename "$1"`"
dir="`dirname "$1"`"
path="`echo "$PATH" | sed 's|.*'"$dir"':||'`"

PATH="$path" exec which "$base"
